### ISSUE TITLE
Plugin not working as expected

### ISSUE THREAD

**Issue by dreamer296** [cometchat-go/ionic-chat-sdk-demo#1]
Hi. I got a problem when install plugin. 
This is error {"code":"101","message":"Error in connection"}
I use valid licenseKey and apiKey.
PLEASE HELP! THANKS

**Comment by adityagokula2210** [comment]
@dreamer296 can you please provide us with some more information like when exactly are you facing this issue. Is it on the click of INITIALIZE COMETCHAT button or on some other event. Also, please share your registered **email address** so that we can check this at our end and try to replicate this issue. 
It would be great if you could also let us know if you have made any modifications to the code.

**Comment by dreamer296** [comment]
hi. grant@fanfoodapp.com is my email.
PLEASE CHECK! THANKS

**Comment by adityagokula2210** [comment]
It appears you are using CometChat Self-Hosted. The demo apps here at GitHub are for CometChat Cloud. For Self-Hosted, please download the sample app for CometChat Self Hosted from the below link:

https://temp.cometchat.com/cordova-chat-sdk-demo(self-hosted).zip

Please refer to the below link for the documentation:

https://docs.cometchat.com/cordova-ionic-plugin/environment-setup/

Hope this helps.
Thanks!!

**Comment by vplaya** [comment]
Hi Guys,

Is the a working link somewhere for cometchat self hosted?
