### ISSUE TITLE
App stuck on splash

### ISSUE THREAD

**Issue by bluelabeldeveloper1** [cometchat-go/ionic-chat-sdk-demo#4]
I clone the repo and its working as expected but when I add this plugin in my existing project after installing app stuck on splash screen.

When I show the log of adb its says 

```
 "Native: deviceready did not fire within 5000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.", source: file:///android_asset/www/build/vendor.js (39488)
"Ionic Native: deviceready did not fire within 5000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.", source: file:///android_asset/www/build/vendor.js (188978)
```

I tried all the possible solution like remove all plugin and install again, remove platform and add again or clear the npm cache etc but none of them help me.

But when I remove the plugin and make build its working fine.

Any help ??

**Comment by adityagokula2210** [comment]
@bluelabeldeveloper1 We have tried to replicate this at our end but were unable to do so. Can you please provide us with more information regarding the same.
Please let us know the Android platform version you are using. Also, it would be great if you could provide additional logs for us to better understand and investigate the issue. 

You can also schedule a short screen sharing session with us using the below link so that we can check the issue at your end.

Link to schedule a session : 
https://www.cometchat.com/schedule-session

Thanks!!
