### ISSUE TITLE
Unable to build android

### ISSUE THREAD

**Issue by azebac** [cometchat-go/ionic-chat-sdk-demo#5]
Everytime that i try to build the example for android  (ionic cordova build --release android) i got this error in MyFirebaseMessagingService.java :

> 
> error: method processCCNotificationData in class CCNotificationHelper cannot be applied to given types;
> required: Context,RemoteMessage,int,int
> found: MyFirebaseMessagingService,RemoteMessage,boolean,int,int
> reason: actual and formal argument lists differ in length
> 

This also happens if i try "ionic cordova run android"

Android details:

> Android Studio 3.2.1
> Build #AI-181.5540.7.32.5056338, built on October 8, 2018
> JRE: 1.8.0_152-release-1136-b06 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0

Ionic version: 3.20.0
npm version: 3.10.10
node version: 6.11.3

**Comment by jitvarpatil** [comment]
We have updated the sample app accordingly. Please take a fresh checkout and try the same.

**Comment by azebac** [comment]
Thanks, now it's working.

**Comment by ehabnaim** [comment]
am still having this issue when using xamarin sample

**Comment by bhoiraashay** [comment]
@ehabnaim  We have updated the Xamarin sample app. Please take a fresh pull and check again.

**Comment by ehabnaim** [comment]
Dear support team,

Thank you for the update

We have  encountered some bugs when deploying xamarin android sample
1- members don't receive notification when sending a message if app is closed
2- App crash sometime when there's image been shared in the chat
3- cannot answer videoncall when app is closed

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bhoiraashay** [comment]
@ehabnaim We'll definitely be looking into your issue. Since this is the Iconic repository, to avoid any further confusion we'll continue the communication on Xamarin repository. 
I've already created an issue for Xamarin, you could check the link below for the updates.

https://github.com/CometChat/xamarin-chat-sdk-android-demo/issues/2

**Comment by ehabnaim** [comment]
Dear support team,

I reported multiple bugs to you and i haven't get the bug fixes untill now, can you please update me on that matter

Regards,
Ehab

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bhoiraashay** [comment]
@ehabnaim We are looking into your issues. Since this issue is related to Xamarin please subscribe to the issue created for Xamarin by visiting the link below. 
https://github.com/CometChat/xamarin-chat-sdk-android-demo/issues/2

You will be notified about the progress once you have subscribed to the issue on the Xamarin repository.
