### ISSUE TITLE
Recent chats showing in contacts tab

### ISSUE THREAD

**Issue by azebac** [cometchat-go/ionic-chat-sdk-demo#7]
As the title says the recent chats are showing in the contacts tab even if the option "Hide Recent Tab" is set in Yes.

**Comment by jitvarpatil** [comment]
We have tested this functionality at our end and it seems to be working fine. After disabling the recent chat from CometChat administration panel the tabs for recent chat is disabled. To understand your query better you can book a session so that we can provide you with a precise solution. You can book a session using the following link :

https://cometchat.com/schedule-session
