### ISSUE TITLE
CCCometChat is not defined ReferenceError

### ISSUE THREAD

**Issue by osvinhybrid** [cometchat-go/ionic-chat-sdk-demo#8]
Error: Uncaught (in promise): ReferenceError: CCCometChat is not defined ReferenceError: CCCometChat is not defined at file:///android_asset/www/build/main.js:315:17 at t.invoke (file:///android_asset/www/build/polyfills.js:3:14976) at Object.zone._inner.zone._inner.fork.onInvoke (file:///android_asset/www/build/vendor.js:5134:33) at t.invoke (file:///android_asset/www/build/polyfills.js:3:14946) at r.run (file:///android_asset/www/build/polyfills.js:3:10143) at file:///android_asset/www/build/polyfills.js:3:20242 at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15660) at Object.zone._inner.zone._inner.fork.onInvokeTask (file:///android_asset/www/build/vendor.js:5125:33) at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15619) at r.runTask (file:///android_asset/www/build/polyfills.js:3:10834)

**Comment by mehtanishant** [comment]
Hello @osvinhybrid,

We have checked the mentioned error however, we are unable to reproduce the error in our sample ionic app. Kindly let us know how you are integrating CometChat in your project so that we can check.
You can also refer below link for integrating CometChat in your project. 

https://github.com/CometChat/ionic-chat-sdk-demo/blob/master/CometChatSample/src/pages/home/home.ts

Feel free to let us know if the issue still exists. You can also book a remote session from:

https://www.cometchat.com/schedule-session

Thank You.
